### ISSUE TITLE
Blank start

### ISSUE THREAD

**Issue by Odaeus** [meeDamian/toggl-cli#10]
Hi,

Writing `toggl start` without a number or name produces `Cannot read property 'NaN' of undefined` as an error. It seems reasonable that it should start the timer with an empty description? I usually start a timer and write in what I did afterwards.

**Comment by meeDamian** [comment]
Yup, that's exactly what should happen… I'll see where the problem is once I have a bit more time.

**Comment by meeDamian** [comment]
Ok, @Odaeus that was an [easy fix](https://github.com/meeDamian/toggl-cli/commit/189f55e9e5e0736e36683c42919376765165e6cd). Should be good now.
