### ISSUE TITLE
Update API Url Domain to api.track.toggl.com

### ISSUE THREAD

**Issue by gilberthdez** [meeDamian/toggl-cli#16]
toggl.com or www.toggl.com will no longer be a supported entry point for the Toggl Track API check:
- https://github.com/toggl/toggl_api_docs
- https://toggl.com/blog/api-documentation-change

**Comment by NoobTW** [comment]
> warning Using the API from toggl.com or www.toggl.com will be dropped at The End of June 2021. Switch to api.track.toggl.com

**Comment by meeDamian** [comment]
Addressed by #18
