### ISSUE TITLE
Continue previous toggl entry

### ISSUE THREAD

**Issue by vjanssens** [meeDamian/toggl-cli#2]
Hi Damian, thank you for this tool, really useful!

I have a question: it possible to continue the last stopped toggl entry? 
We work heavily with projects and because it's not yet possible to add a project to a toggl entry it would be useful to continue with the previous entry (as it already has a project attached, most of the time).

**Comment by meeDamian** [comment]
Hey, sure, I'll look into it :). Which mode you use more?

**Comment by meeDamian** [comment]
@vjanssens Fixed for both modes. let me know what you think.
