### ISSUE TITLE
no such file or dir in /usr/bin/env

### ISSUE THREAD

**Issue by musichen** [meeDamian/toggl-cli#4]
Installed toggl-cli  via     npm install -g toggl-cli
I'm using nvm,  I have  node 1.8.4 by default and  second version I use is  5.3.0

NODE_PATH is set correctly to global node_modules

Whenever I run   
`$ toggl`

 I get this error:
`/usr/bin/env: node --harmony_destructuring --harmony_default_parameters --harmony_rest_parameters: No such file or directory`

**Comment by andrewhowdencom** [comment]
I am also getting this issue. 

`$ uname -a
Linux jade 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

`$ node --version
v5.9.1
`

Removing env + args from the shebang just yields a different error.

**Comment by meeDamian** [comment]
I'm not able to reproduce (mac). Note that only node v5+ is currently supported and running it against previous versions does, in fact, return similar error:

```
$ nvm install 1.8.3
$ node --version
v1.8.4
$ toggl
node: bad option: --harmony_destructuring
node: bad option: --harmony_default_parameters
node: bad option: --harmony_rest_parameters
```

In case you installed it with node older than v5.0, try:
```
$ npm rm -g toggl-cli
$ nvm i 5.9
$ npm i -g toggl-cli
$ toggl
```

Exact reprod steps or PRs welcomed :)

**Comment by musichen** [comment]
Steps i made

```
$ npm rm -g toggl-cli
 $ nvm i 5.9
$ nvm use 5.9 && node -v
$  v5.9.1
 $ npm i -g toggl-cli
 $ toggl
/usr/bin/env: node --harmony_destructuring --harmony_default_parameters 
--harmony_rest_parameters: No such file or directory
```
               It keeps looking for   node in  /usr/bin/env with those   harmony parameters.

My Linux version and Kernel version:

```
$ uname -a
$ Linux musichenpc 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ nvm --version
$ 0.30.1
```

Any ideas what might be wrong?

**Comment by alxgnon** [comment]
Can you try my fix, @musichen?

```bash
$ git clone https://github.com/alxgnon/toggl-cli -b fix-issue-4
$ npm install -g ./toggl-cli
$ toggl --logo
```

**Comment by meeDamian** [comment]
Fix pushed and published, call: `npm -g update toggl-cli`

**Comment by musichen** [comment]
Thank you Alexandre!   Your fix removed the issue.
